### PR TITLE
allow double dash for modifier #112

### PR DESCRIPTION
**Pull request by ausminternet**
I extended the bem preset to accept `--` as modifier seperator as Harry Roberts BEM style suggests.

### CODE REVIEW

**Comment by simonsmith** [comment]
Thanks for this @ausminternet !

Are you able to add a unit test as well, just to validate this addition?

**Comment by ausminternet** [comment]
Sure, I added some additional classes to the fixtures.

**Comment by sirctseb** [comment]
This would be very useful for us. Are there plans to merge this?

**Comment by sirctseb** [comment]
@simonsmith gentle bump to consider merging this if you have a moment. I'm happy to help if it needs any updates

**Comment by simonsmith** [comment]
Whoops, I missed this quite badly. Apologies all

**Pull request merged**
