### PR TITLE
Add implicitComponents and implicitUtilities option

### LINKED ISSUE #88: Feature: automate file-name definititions
This really perhaps really a feature-request for [`stylelint-selector-bem-pattern`](https://github.com/davidtheclark/stylelint-selector-bem-pattern), but I'll leave it here since that module mostly wraps this one.

I know explicit definitions are great, and they work for many people, but… I'm lazy.  I would like to enforce our rules BEM rules.

Let's say for an example project we standardize on SUIT, and mandate it into our component file-structure. File-structure looks something like:

```
components/DogCard/DogCard.js
components/DogCard/DogCard.css
components/DogList/DogList.js
components/DogList/DogList.css
```

So, we setup our config

``` json
"rules": {
  "plugin/selector-bem-pattern": {
    "preset": "suit"
  }
}
```

Now, we have something like 50 components to add a "define" block too to enforce our pattern and manually enforce new components include the `define`.

This is okay, but if we just implicit the `define` from the filename.

``` json
"rules": {
  "plugin/selector-bem-pattern": {
    "preset": "suit",
    "implyFilenameDefine": true
  }
}
```

Now, when `components/DogCard/DogCard.css` is passed to the linter we imply

``` js
/** @define DogCard */
```

If someone wants to add a utility lib, no problem, they'll get a warning can use `utilities` to opt-out.

``` js
/** @define utilities */
```

I'm sure some work will need to be done to `stylelint-selector-bem-pattern` as well, but it probably starts here.

//cc @davidtheclark

### PR DESCRIPTION
**Pull request by simonsmith**
This is #93 but with a couple changes (https://github.com/postcss/postcss-bem-linter/commit/5288ab6ad8e0fce55ede9b47d236f7ba0caa25b2) and (https://github.com/postcss/postcss-bem-linter/commit/4da17567604629f04c55bdcf87e60905c9812eff).

Fixes #88 

@seamusleahy If you're happy with those changes I'll get this merged.

### CODE REVIEW

**Comment by seamusleahy** [comment]
Looks good to me.

I saw your comment about reverting the isArray.

**Comment by AndyOGo** [comment]
awesome
May I ask when a new release is planned?

**Comment by simonsmith** [comment]
I'll publish it today :)

**Comment by simonsmith** [comment]
Published in `2.7.0`. Thanks again to @seamusleahy

**Pull request merged**
